/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kurzawsk.betting.common;

public class Library {
    public boolean someLibraryMethod() {
        return false;
    }
}
